services:
  app:
    image: ypd-langchain-app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      #- AWS_REGION=${AWS_REGION} # .env で設定
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      #- ASANA_ACCESS_TOKEN=${ASANA_ACCESS_TOKEN} # .env で設定
      #- BEDROCK_KNOWLEDGE_BASE_ID=${BEDROCK_KNOWLEDGE_BASE_ID} # .env で設定
    env_file:
      - ../.env       
